branches:
  only:
  - master
bundler_args: "--without production --deployment --jobs=3 --retry=3"
cache: bundler
language: ruby
rvm:
- 2.5.3
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external
