[build.environment]
  NODE_VERSION = "17.6"

[context.deploy-preview]
  command = "JEKYLL_ENV=development jekyll build --future"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
